#!/usr/bin/env python3
# app.py - Application Bootstrap
# Generated by xtUML to Python Compiler

from __future__ import annotations
import sys

# Import runtime
from runtime.storage import ObjectStore
from runtime.relationship import relate, unrelate, select_related, clear_relationships
from runtime.base import RuntimeServices

# Import model classes
from models.Product import Product
from models.VendingMachine import VendingMachine
from models.UserInterface import UserInterface
from models.Transaction import Transaction
from models.Payment import Payment
from models.PaymentService import PaymentService
from models.InventoryService import InventoryService
from models.Dispenser import Dispenser

def setup_demo_data():
    """Create demo instances for testing"""
    print('Setting up demo data...')
    instances = {}

    # Create Product instance
    instances['product'] = Product._create_instance(id='product_1')
    print(f"  Created: {instances['product']}")

    # Create VendingMachine instance
    instances['vendingmachine'] = VendingMachine._create_instance(id='vendingmachine_1')
    print(f"  Created: {instances['vendingmachine']}")

    # Create UserInterface instance
    instances['userinterface'] = UserInterface._create_instance(id='userinterface_1')
    print(f"  Created: {instances['userinterface']}")

    # Create Transaction instance
    instances['transaction'] = Transaction._create_instance(id='transaction_1')
    print(f"  Created: {instances['transaction']}")

    # Create Payment instance
    instances['payment'] = Payment._create_instance(id='payment_1')
    print(f"  Created: {instances['payment']}")

    # Seed product attributes so selection works
    product = instances['product']
    product.set_attr('productCode', 'A1')
    product.set_attr('name', 'Aqua 600ml')
    product.set_attr('price', 7000.0)
    product.set_attr('stock', 3)

    # Relate VM to UI across R2 for messaging
    vm = instances['vendingmachine']
    ui = instances['userinterface']
    relate('R2', vm, ui)

    return instances

def run():
    """Main entry point"""
    print('='*60)
    print('vending_machine_qris - System Start')
    print('='*60)

    # Clean slate per run
    ObjectStore.clear()
    clear_relationships()

    # Setup demo data
    instances = setup_demo_data()

    # Interactive loop
    main_instance = instances.get('vendingmachine')
    product = instances.get('product')

    def show_state():
        if main_instance and hasattr(main_instance, 'sm'):
            print(f"Current state: {main_instance.sm.get_current_state()}")
        if product:
            print(f"Product {product.get_attr('productCode')} stock={product.get_attr('stock')} price={product.get_attr('price')}")

    actions = {
        '1': 'Select product',
        '2': 'Payment success',
        '3': 'Payment failed',
        '4': 'Show state',
        'x': 'Exit'
    }

    while True:
        print('\nMenu:')
        for k, v in actions.items():
            print(f"  {k}. {v}")
        choice = input('Pilih opsi: ').strip().lower()

        if choice == '1':
            code = input('Masukkan productCode (default A1): ').strip() or (product.get_attr('productCode') if product else '')
            if main_instance:
                main_instance.dispatch_event('ProductSelected', p_productCode=code)
        elif choice == '2':
            if main_instance:
                main_instance.dispatch_event('PaymentSuccess')
        elif choice == '3':
            if main_instance:
                main_instance.dispatch_event('PaymentFailed')
        elif choice == '4':
            show_state()
        elif choice == 'x':
            print('Exiting...')
            break
        else:
            print('Opsi tidak dikenal')

    print('\nSimulation selesai.')
    return instances

if __name__ == '__main__':
    instances = run()
    
    # Interactive mode hint
    print('\n--- Interactive Mode ---')
    print('Available instances:', list(instances.keys()))